projectcapstone1:
  outputs:
    dev:
      dataset: order
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /workspaces/Project-Capstone-DS525/Capstone-project/key/project-capstone-422211-4cd38acf1283.json
      location: US
      method: service-account
      priority: interactive
      project: project-capstone-422211
      threads: 1
      type: bigquery
  target: dev
